FROM ubuntu:24.04


########################################################################################################################
# Install Dependencies                                                                                                 #
########################################################################################################################
USER root

RUN <<EOF
    apt-get update
    # Basic Requirements for compiling the code
    apt-get -y install g++-13 cmake git
    # Needed for the development environment
    apt-get -y install cppcheck gdb clang-format
    # Needed for the documentation
    apt-get -y install doxygen graphviz texlive-base
    #
    # Dependencies (libdl)
    apt-get -y install libopenblas-dev libssl-dev zlib1g-dev
    # Dependencies (libdl)
    apt-get -y install libboost-iostreams-dev
EOF



########################################################################################################################
# Create User                                                                                                          #
########################################################################################################################
# Change root Password to 1234
RUN echo 'root:1234' | chpasswd
# Create new user: "dev"
RUN useradd -ms /bin/bash dev
USER dev