var searchData=
[
  ['va_5flist_1367',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray_1368',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['valid_1369',['valid',['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()'],['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()']]],
  ['value_1370',['value',['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['../structdl_1_1TransformerConf.html#ae202da4a3e1a4acf317b92716c35eed1',1,'dl::TransformerConf::value()'],['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()']]],
  ['value_5fcomp_1371',['value_comp',['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()']]],
  ['value_5fcompare_1372',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map::value_compare'],['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap::value_compare']]],
  ['value_5for_1373',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional']]],
  ['vector_1374',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std::vector'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['vector_3c_20char_20_3e_1375',['vector&lt; char &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e_1376',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20dl_3a_3atrainerobserver_20_3e_20_3e_1377',['vector&lt; std::unique_ptr&lt; dl::TrainerObserver &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20dl_3a_3atransformerencoder_20_3e_20_3e_1378',['vector&lt; std::unique_ptr&lt; dl::TransformerEncoder &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vfprintf_1379',['vfprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vfscanf_1380',['vfscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vfwprintf_1381',['vfwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vfwscanf_1382',['vfwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vprintf_1383',['vprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vscanf_1384',['vscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vsnprintf_1385',['vsnprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsprintf_1386',['vsprintf',['http://en.cppreference.com/w/cpp/io/c/vfprintf.html',1,'std']]],
  ['vsscanf_1387',['vsscanf',['http://en.cppreference.com/w/cpp/io/c/vfscanf.html',1,'std']]],
  ['vswprintf_1388',['vswprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vswscanf_1389',['vswscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]],
  ['vwprintf_1390',['vwprintf',['http://en.cppreference.com/w/cpp/io/c/vfwprintf.html',1,'std']]],
  ['vwscanf_1391',['vwscanf',['http://en.cppreference.com/w/cpp/io/c/vfwscanf.html',1,'std']]]
];
