var searchData=
[
  ['dataloader_1662',['Dataloader',['../classdl_1_1Dataloader.html',1,'dl']]],
  ['dataloader_3c_20r_28args_2e_2e_2e_29_3e_1663',['Dataloader&lt; R(Args...)&gt;',['../classdl_1_1Dataloader_3_01R_07Args_8_8_8_08_4.html',1,'dl']]],
  ['dataset_1664',['Dataset',['../classdl_1_1Dataset.html',1,'dl']]],
  ['dataset_3c_20float_28query_2c_20document_29_3e_1665',['Dataset&lt; float(Query, Document)&gt;',['../classdl_1_1Dataset.html',1,'dl']]],
  ['dataset_3c_20r_28args_2e_2e_2e_29_3e_1666',['Dataset&lt; R(Args...)&gt;',['../classdl_1_1Dataset_3_01R_07Args_8_8_8_08_4.html',1,'dl']]],
  ['dataset_3c_20void_28query_2c_20document_2c_20document_29_3e_1667',['Dataset&lt; void(Query, Document, Document)&gt;',['../classdl_1_1Dataset.html',1,'dl']]],
  ['deca_1668',['deca',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['decay_1669',['decay',['http://en.cppreference.com/w/cpp/types/decay.html',1,'std']]],
  ['deci_1670',['deci',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['default_5fdelete_1671',['default_delete',['http://en.cppreference.com/w/cpp/memory/default_delete.html',1,'std']]],
  ['default_5frandom_5fengine_1672',['default_random_engine',['http://en.cppreference.com/w/cpp/numeric/random.html',1,'std']]],
  ['defer_5flock_5ft_1673',['defer_lock_t',['http://en.cppreference.com/w/cpp/thread/lock_tag_t.html',1,'std']]],
  ['deque_1674',['deque',['http://en.cppreference.com/w/cpp/container/deque.html',1,'std']]],
  ['device_1675',['Device',['../classdl_1_1Device.html',1,'dl']]],
  ['discard_5fblock_5fengine_1676',['discard_block_engine',['http://en.cppreference.com/w/cpp/numeric/random/discard_block_engine.html',1,'std']]],
  ['discrete_5fdistribution_1677',['discrete_distribution',['http://en.cppreference.com/w/cpp/numeric/random/discrete_distribution.html',1,'std']]],
  ['divides_1678',['divides',['http://en.cppreference.com/w/cpp/utility/functional/divides.html',1,'std']]],
  ['document_1679',['Document',['../structir_1_1Document.html',1,'ir']]],
  ['dof_1680',['DOF',['../structdl_1_1DOF.html',1,'dl']]],
  ['domain_5ferror_1681',['domain_error',['http://en.cppreference.com/w/cpp/error/domain_error.html',1,'std']]],
  ['duration_1682',['duration',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['duration_5fvalues_1683',['duration_values',['http://en.cppreference.com/w/cpp/chrono/duration_values.html',1,'std::chrono']]],
  ['dynarray_1684',['dynarray',['http://en.cppreference.com/w/cpp/container/dynarray.html',1,'std']]]
];
