var searchData=
[
  ['dataloader_1654',['Dataloader',['../classdl_1_1Dataloader.html',1,'dl']]],
  ['dataloader_3c_20r_28args_2e_2e_2e_29_3e_1655',['Dataloader&lt; R(Args...)&gt;',['../classdl_1_1Dataloader_3_01R_07Args_8_8_8_08_4.html',1,'dl']]],
  ['dataset_1656',['Dataset',['../classdl_1_1Dataset.html',1,'dl']]],
  ['dataset_3c_20float_28query_2c_20document_29_3e_1657',['Dataset&lt; float(Query, Document)&gt;',['../classdl_1_1Dataset.html',1,'dl']]],
  ['dataset_3c_20r_28args_2e_2e_2e_29_3e_1658',['Dataset&lt; R(Args...)&gt;',['../classdl_1_1Dataset_3_01R_07Args_8_8_8_08_4.html',1,'dl']]],
  ['dataset_3c_20void_28query_2c_20document_2c_20document_29_3e_1659',['Dataset&lt; void(Query, Document, Document)&gt;',['../classdl_1_1Dataset.html',1,'dl']]],
  ['deca_1660',['deca',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['decay_1661',['decay',['http://en.cppreference.com/w/cpp/types/decay.html',1,'std']]],
  ['deci_1662',['deci',['http://en.cppreference.com/w/cpp/numeric/ratio/ratio.html',1,'std']]],
  ['default_5fdelete_1663',['default_delete',['http://en.cppreference.com/w/cpp/memory/default_delete.html',1,'std']]],
  ['default_5frandom_5fengine_1664',['default_random_engine',['http://en.cppreference.com/w/cpp/numeric/random.html',1,'std']]],
  ['defer_5flock_5ft_1665',['defer_lock_t',['http://en.cppreference.com/w/cpp/thread/lock_tag_t.html',1,'std']]],
  ['deque_1666',['deque',['http://en.cppreference.com/w/cpp/container/deque.html',1,'std']]],
  ['device_1667',['Device',['../classdl_1_1Device.html',1,'dl']]],
  ['discard_5fblock_5fengine_1668',['discard_block_engine',['http://en.cppreference.com/w/cpp/numeric/random/discard_block_engine.html',1,'std']]],
  ['discrete_5fdistribution_1669',['discrete_distribution',['http://en.cppreference.com/w/cpp/numeric/random/discrete_distribution.html',1,'std']]],
  ['divides_1670',['divides',['http://en.cppreference.com/w/cpp/utility/functional/divides.html',1,'std']]],
  ['document_1671',['Document',['../structir_1_1Document.html',1,'ir']]],
  ['domain_5ferror_1672',['domain_error',['http://en.cppreference.com/w/cpp/error/domain_error.html',1,'std']]],
  ['duration_1673',['duration',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['duration_5fvalues_1674',['duration_values',['http://en.cppreference.com/w/cpp/chrono/duration_values.html',1,'std::chrono']]],
  ['dynarray_1675',['dynarray',['http://en.cppreference.com/w/cpp/container/dynarray.html',1,'std']]]
];
