FROM ubuntu:24.04


########################################################################################################################
# Install Dependencies                                                                                                 #
########################################################################################################################
USER root

RUN <<EOF
    add-apt-repository universe
    apt-get update
    #
    # Basic Requirements for compiling the code
    apt-get -y install g++-14 cmake git
    # Needed for the development environment
    apt-get -y install cppcheck gdb clang-format
    # Needed for the documentation
    apt-get -y install doxygen graphviz texlive-base
    #
    # Dependencies (libdl)
    apt-get -y install libopenblas-dev libssl-dev zlib1g-dev
    # Dependencies (libir)
    apt-get -y install libboost-iostreams-dev
    #
    # Install Apache Arrow:
    apt install -y -V ca-certificates lsb-release wget
    wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
    apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
    apt update
    apt install -y -V libarrow-dev
EOF



########################################################################################################################
# Create User                                                                                                          #
########################################################################################################################
# Change root Password to 1234
RUN echo 'root:1234' | chpasswd
# Create new user: "dev"
RUN useradd -ms /bin/bash dev
USER dev